### ISSUE TITLE
typo in installation instructions

### ISSUE THREAD

**Issue by ProjectRamo** [fynnfluegge/rocketnotes#139]
It says:

> docker-compuse up -d

when clearly it means:

> docker-compose up -d

I tried to submit the PR but for some reason it would not authenticate me but this is so small I just put it here.

**Comment by fynnfluegge** [comment]
Thanks @ProjectRamo, just to be curious, what is the problem when raising a PR?

**Comment by ProjectRamo** [comment]
Sorry, I was not clear. I just cloned it locally without forking it to play around. On Sep 25, 2024, at 1:59 AM, Fynn Flügge ***@***.***> wrote:﻿
Thanks @ProjectRamo, just to be curious, what is the problem when raising a PR?
