### ISSUE TITLE
bug(webapp): document selection highlight does not work for childs

### ISSUE THREAD

**Issue by fynnfluegge** [fynnfluegge/rocketnotes#65]
When selecting a child node in the document tree the highlight color does not appear anymore.

**Comment by vishalpawarR** [comment]
@fynnfluegge Hey can you please provide me the proper steps for reproducing the issue so that I can help you with this quickly? Please also provide screenshot for better understanding.

**Comment by fynnfluegge** [comment]
Hey @vishalpawarR thanks for your help! 🙌
You can reproduce the bug by simply selecting a child document in the document tree:
![Screenshot 2023-06-14 at 21 59 47](https://github.com/fynnfluegge/rocketnotes/assets/16321871/b608e3a3-910f-4c4c-8b8f-3a6e3fedaeac)

You can see in this screenshot I selected `ZSH Setup` and afterwards selected the `ranger` document, which is a child of it.
But the highlighted item in the document tree is still `ZSH Setup`.
The expected behaviour would be highlighting `ranger`. You can reproduce it with any child document.

I have the feeling the bug occurred in one of the last commits if this might help you.
If you need more help feel free to ask! 🙂

**Comment by fynnfluegge** [comment]
Hey @vishalpawarR I have an idea about this. In #64 I changed the behaviour of the selection of a document with an onchange event by using `(click)="openItem(node.id)"` instead of calling a routerlink. I forgot to do this for the parent nodes with `hasChild` property. That should be a quickfix for now, but I think the highlight color does not work anymore because `routerLinkActive="active-node"` does not work with the onchange event.

**Comment by fynnfluegge** [comment]
Pushed a quickfix here https://github.com/fynnfluegge/rocketnotes/commit/45e68dd8803b6e132bef0b4554feb31942cf44d1 because parent selection was broken after selecting a child. Hightlight color after selection still does not work currently.

**Comment by fynnfluegge** [comment]
> @fynnfluegge Hey can you please provide me the proper steps for reproducing the issue so that I can help you with this quickly? Please also provide screenshot for better understanding.

Hey @vishalpawarR how you doing? Feel free to let me know if you need some help or introduction to the project 🙌
